### ISSUE TITLE
About MTR-A

### ISSUE THREAD

**Issue by zen-d** [sshaoshuai/MTR#13]
@sshaoshuai Hi, thank you for this wonderful work! 

MTR is great, while MTR-A achieves more impressive performance. So would you be kind enough to also release the code for reproducing MTR-A? Thanks.

**Comment by sshaoshuai** [comment]
The performance of MTRA is achieved by the model ensemble of several MTR variants, so current codes actually are already all the key modules for reproducing MTRA. 
Since the model ensemble parts are not related to the MTR framework, so currently I prefer to keep the codebase clean and the users can explore their only model ensemble strategies.
