### ISSUE TITLE
about the ops folder

### ISSUE THREAD

**Issue by chrisxuxuhui** [sshaoshuai/MTR#57]
1，with ops folder ,could I load by pt or onnx , while we want infer with c++ about deployment?
2,   will you have ops with pytorch version ? 
3,why use cuda and c++ program ops?
4, how long could I train with only one A5000?

**Comment by sshaoshuai** [comment]
1. You need to adapt some interfaces for deployment. 
2. No
3. Because it is more memory-efficient, but you can also write the local attention with native PyTorch. 
4. I do not have A5000 GPUs and can not answer this question. But it should be more than one week if you train the model with a single GPU on the 100% training dataset.
