### ISSUE TITLE
About global attention

### ISSUE THREAD

**Issue by 14916** [sshaoshuai/MTR#59]
In the configuration file, there is an option called USE_LOCAL_ATTN. Changing it to False and using global attention can lead to several errors during training. Could you please provide guidance on how to utilize global attention effectively?

**Comment by sshaoshuai** [comment]
Theoretically, you can just change it to False. Since I didn't check the global attention carefully in this refactored codebase, there may exist some small problems due to different interfaces. If you would like to use global attention, then you need to adjust the code slightly according to the reported errors.

**Comment by blueardour** [comment]
@14916 Have you work out the network with only global attention?  I also have the requirement as I would deploy the network on device. KNN and the customized MultiHeadAttention are chanllenging to deploy.

**Comment by blueardour** [comment]
I finished the code revision, however the GPU memory cost increased a lot. On A4000 with 48GB GDDR， local attetntion version enable bs=20 per gpu, however it only support bs=8 per gpu for revised version.
