### ISSUE TITLE
About data pre-processing

### ISSUE THREAD

**Issue by toyot-li** [sshaoshuai/MTR#8]
Hi, @sshaoshuai Thanks for your wonderful work!

When I try the code first for data pre-processing, it keeps poping out so many lines of errors like below
```bash
2023-02-24 00:55:16.221545: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```
and I cannot see the tqdm progress bar. Is there anything wrong with the process?

In addition, may I know how much time this processing usually costs?

**Comment by sshaoshuai** [comment]
In order to check the data processing state, you can check whether the number of processed files is increasing (data/waymo/processed_scenarios_training). 

Our data processing code just extracts data from tfrecord and saves as our defined data format, so it depends on the tensorflow environment. I just find that it varies a lot with different tensorflow environments. On my side, sometimes it just takes several hours, and sometimes it may take 1 day. 

I appreciate it if someone can find the reason and see how to make the speed of data processing faster and more stable (I guess the reason lies in tensorflow environment and multiprocessing)

**Comment by sshaoshuai** [comment]
If the number of files keeps increasing, I think the generated files should be fine. 
Actually the data processing does not use any CUDA operation, so I think you can simply disable the GPU by using  CUDA_VISIBLE_DEVICES=

**Comment by sshaoshuai** [comment]
The number of training files should be 487002. I think some threads have broken. 
As I mentioned before, I think there may be some problems related to the tensorflow and multiprocessing. (Actually I can run it smoothly several months ago, but I am not sure what happens currently.)

(1) Can you try to change the following line:
https://github.com/sshaoshuai/MTR/blob/master/mtr/datasets/waymo/data_preprocess.py#L225

to another alternative multiprocessing way: 
```python
with futures.ThreadPoolExecutor(num_workers) as executor:
    data_infos = executor.map(func, src_files)
    data_infos = list(data_infos)
```

(2) If it still does not work, you can just run `process_waymo_data_with_scenario_proto ` sequentially without using multiprocessing. 

Please let me know whether it works.

**Comment by BJHYZJ** [comment]
![image](https://user-images.githubusercontent.com/74347732/221575144-7f5665a7-edf0-427a-a6e2-c8df60e0bf94.png)
I also encountered some problems in data preprocessing.

**Comment by SiyuanHuang95** [comment]
Hi, @zen-d. Could you share a complete list of your pip package dependencies since I have met the problem stated in [Issue](https://github.com/sshaoshuai/MTR/issues/9#issue-1601508777), which could be related to the pip version? BTW, whats your hardware information?
